### ISSUE TITLE
Error while push model to ECR .. Not able to build image

### ISSUE THREAD

**Issue by mailamiton** [aws-samples/codepipeline-ecr-build-sf-execution#3]
Code Build Issue :: ---

copying src/gevent/tests/tests_that_dont_do_leakchecks.txt -> build/lib.linux-x86_64-2.7/gevent/tests
--
926 | copying src/gevent/tests/test_server.key -> build/lib.linux-x86_64-2.7/gevent/tests
927 | copying src/gevent/tests/server.key -> build/lib.linux-x86_64-2.7/gevent/tests
928 | running build_ext
929 | generating cffi module 'build/temp.linux-x86_64-2.7/gevent.libuv._corecffi.c'
930 | creating build/temp.linux-x86_64-2.7
931 | Running '(cd  "/tmp/pip-install-9he335/gevent/deps/libev"  && sh ./configure -C > configure-output.txt )' in /tmp/pip-install-9he335/gevent
932 | configure: error: in `/tmp/pip-install-9he335/gevent/deps/libev':
933 | configure: error: no acceptable C compiler found in $PATH
934 | See `config.log' for more details
935 | Traceback (most recent call last):
936 | File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
937 | main()
938 | File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
939 | json_out['return_val'] = hook(**hook_input['kwargs'])
940 | File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
941 | metadata_directory)
942 | File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 209, in build_wheel
943 | wheel_directory, config_settings)
944 | File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
945 | self.run_setup()
946 | File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 243, in run_setup
947 | self).run_setup(setup_script=setup_script)
948 | File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 142, in run_setup
949 | exec(compile(code, __file__, 'exec'), locals())
950 | File "setup.py", line 481, in <module>
951 | run_setup(EXT_MODULES)
952 | File "setup.py", line 465, in run_setup
953 | "signal_os_incompat = gevent.monkey:_subscribe_signal_os",
954 | File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 162, in setup
955 | return distutils.core.setup(**attrs)
956 | File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
957 | dist.run_commands()
958 | File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
959 | self.run_command(cmd)
960 | File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
961 | cmd_obj.run()
962 | File "/usr/local/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 299, in run
963 | self.run_command('build')
964 | File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
965 | self.distribution.run_command(command)
966 | File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
967 | cmd_obj.run()
968 | File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
969 | self.run_command(cmd_name)
970 | File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
971 | self.distribution.run_command(command)
972 | File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
973 | cmd_obj.run()
974 | File "/tmp/pip-build-env-covKid/overlay/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 143, in run
975 | ext.sources[0] = make_mod(self.build_temp, pre_run)
976 | File "/tmp/pip-build-env-covKid/overlay/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 128, in make_mod
977 | pre_run(ext, ffi)
978 | File "/tmp/pip-install-9he335/gevent/_setuputils.py", line 364, in pre_run
979 | action()
980 | File "/tmp/pip-install-9he335/gevent/_setuplibev.py", line 55, in configure_libev
981 | system(libev_configure_command)
982 | File "/tmp/pip-install-9he335/gevent/_setuputils.py", line 195, in system
983 | if _system(cmd, cwd=cwd, env=env, **kwargs):
984 | File "/tmp/pip-install-9he335/gevent/_setuputils.py", line 191, in _system
985 | return check_call(cmd, cwd=cwd, env=env, **kwargs)
986 | File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
987 | raise CalledProcessError(retcode, cmd)
988 | subprocess.CalledProcessError: Command '(cd  "/tmp/pip-install-9he335/gevent/deps/libev"  && sh ./configure -C > configure-output.txt )' returned non-zero exit status 1
989 | ----------------------------------------
990 | ERROR: Failed building wheel for gevent
991 | Failed to build gevent
992 | ERROR: Could not build wheels for gevent which use PEP 517 and cannot be installed directly
993 | The command '/bin/sh -c wget https://bootstrap.pypa.io/pip/2.7/get-pip.py && python get-pip.py &&     pip install numpy==1.16.2 scipy==1.2.1 scikit-learn==0.20.2 pandas flask gevent gunicorn &&         (cd /usr/local/lib/python2.7/dist-packages/scipy/.libs; rm *; ln ../../numpy/.libs/* .) &&         rm -rf /root/.cache' returned a non-zero code: 1
994 |  
995 | [Container] 2021/10/04 11:13:41 Command did not exit successfully docker build --tag "$IMAGE_URI" . exit status 1
996 | [Container] 2021/10/04 11:13:41 Phase complete: BUILD State: FAILED
997 | [Container] 2021/10/04 11:13:41 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: docker build --tag "$IMAGE_URI" .. Reason: exit status 1
998 | [Container] 2021/10/04 11:13:41 Entering phase POST_BUILD
999 | [Container] 2021/10/04 11:13:41 Running command docker push "$IMAGE_URI"
1000 | The push refers to a repository [******************.dkr.ecr.eu-west-1.amazonaws.com/codepipeline-ecr-build-sf-execution-repository-hnkbim8hx68j]
1001 | An image does not exist locally with the tag: **************.dkr.ecr.eu-west-1.amazonaws.com/codepipeline-ecr-build-sf-execution-repository-hnkbim8hx68j
1002 |  
1003 | [Container] 2021/10/04 11:13:41 Command did not exit successfully docker push "$IMAGE_URI" exit status 1
1004 | [Container] 2021/10/04 11:13:41 Phase complete: POST_BUILD State: FAILED
1005 | [Container] 2021/10/04 11:13:41 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: docker push "$IMAGE_URI". Reason: exit status 1
1006 | [Container] 2021/10/04 11:13:41 Expanding base directory path: .

**Comment by mailamiton** [comment]
figured it Out .. In Dockerfile - change "gevent"  to  "gevent==1.5.0" 


RUN wget https://bootstrap.pypa.io/pip/2.7/get-pip.py && python get-pip.py && \
    pip install numpy==1.16.2 scipy==1.2.1 scikit-learn==0.20.2 pandas flask gevent==1.5.0 gunicorn && \
        (cd /usr/local/lib/python2.7/dist-packages/scipy/.libs; rm *; ln ../../numpy/.libs/* .) && \
        rm -rf /root/.cache

**Comment by mailamiton** [comment]
Above Changes pushed the image in ecr
